stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - talosai-deploy
  only:
    - main
  script:
    - |
      cat > .env <<EOF
      POSTGRES_PORT=${POSTGRES_PORT}
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      DATABASE_URL=${DATABASE_URL}

      DEV=${DEV}
      BACKEND_PORT=${BACKEND_PORT}
      JWT_ALG=${JWT_ALG}
      REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      
      CREWAI_TRACING_ENABLED=${CREWAI_TRACING_ENABLED}
      OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      GEMINI_API_KEY=${GEMINI_API_KEY}
      GEMINI_MODEL=${GEMINI_MODEL}
      PLANNER_MODEL=${PLANNER_MODEL}
      SCANNER_MODEL=${SCANNER_MODEL}
      TESTER_MODEL=${TESTER_MODEL}
      SUMMARIZER_MODEL=${SUMMARIZER_MODEL}
      CRITIC_MODEL=${CRITIC_MODEL}
      REPORTER_MODEL=${REPORTER_MODEL}
      EOF
    # If DEV=true: database reset
    - >
      if [ "$DEV" = "true" ]; then
        docker compose -f docker-compose.prod.yml down -v;
      fi
    # Build images in background
    - docker compose -f docker-compose.prod.yml build
    #
    - >
      if [ "$DEV" = "true" ]; then
        docker compose -f docker-compose.prod.yml up -d db;
        until docker compose -f docker-compose.prod.yml exec -T db pg_isready -U postgres; do
          sleep 1;
        done;
      fi
    # Alembic migration using new image
    - docker compose -f docker-compose.prod.yml run --rm backend alembic upgrade head
    # Seed database
    - >
      if [ "$DEV" = "true" ] && [ -f ~/seed.sql ]; then
        docker compose -f docker-compose.prod.yml cp ~/seed.sql db:/tmp/seed.sql;
        docker compose -f docker-compose.prod.yml exec -T db psql -U postgres -d talos_db -f /tmp/seed.sql;
        docker compose -f docker-compose.prod.yml exec -T db rm /tmp/seed.sql;
      fi
    # Docker replaces only changed images
    - docker compose -f docker-compose.prod.yml up -d
