services:

  db:
    image: postgres:16-alpine
    container_name: talos_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 3s
      interval: 3s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - talos_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: talos_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - talos_network
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

networks:
  talos_network:
    driver: bridge
    name: talos_network

volumes:
  postgres_data: