"""added_user_sessions_table

Revision ID: 10e5f06f27ae
Revises: 6aa5fe7799d5
Create Date: 2026-05-18 10:48:06.232677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10e5f06f27ae'
down_revision: Union[str, Sequence[str], None] = '6aa5fe7799d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'last_active',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_ip'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_uid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_constraint(op.f('user_sessions_uuid_key'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_sessions_uuid'), 'user_sessions', ['uuid'], unique=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='user_role'),
               type_=sa.Enum('admin', 'user', 'auditor', name='userrole', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'user'::user_role"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_uuid_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_uuid_key'), 'users', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', 'auditor', name='userrole', native_enum=False),
               type_=postgresql.ENUM('admin', 'user', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.drop_index(op.f('ix_user_sessions_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.create_unique_constraint(op.f('user_sessions_uuid_key'), 'user_sessions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_uid'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_uid'), 'user_sessions', ['uuid'], unique=False)
    op.create_index(op.f('ix_user_sessions_ip'), 'user_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_sessions', 'last_active',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
