"""add missions tables

Revision ID: 4a524ed3cf25
Revises: d10cc1a878ed
Create Date: 2026-10-10 12:42:27.658694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a524ed3cf25'
down_revision: Union[str, Sequence[str], None] = 'd10cc1a878ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_ip', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('orchestrator_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_index(op.f('ix_missions_user_uid'), 'missions', ['user_uid'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('mission_uid', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_uid'], ['missions.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_index(op.f('ix_findings_mission_uid'), 'findings', ['mission_uid'], unique=False)
    op.create_table('mission_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_uid', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_uid'], ['missions.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_ports_id'), 'mission_ports', ['id'], unique=False)
    op.create_index(op.f('ix_mission_ports_mission_uid'), 'mission_ports', ['mission_uid'], unique=False)
    op.drop_index(op.f('ix_user_sessions_uuid'), table_name='user_sessions')
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_index(op.f('ix_user_sessions_uuid'), 'user_sessions', ['uuid'], unique=False)
    op.drop_index(op.f('ix_mission_ports_mission_uid'), table_name='mission_ports')
    op.drop_index(op.f('ix_mission_ports_id'), table_name='mission_ports')
    op.drop_table('mission_ports')
    op.drop_index(op.f('ix_findings_mission_uid'), table_name='findings')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_missions_user_uid'), table_name='missions')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
