from crewai import Crew, Process, Task

from app.agents.critic import get_critic_agent
from app.agents.planner import get_planner_agent
from app.agents.reporter import get_reporter_agent
from app.agents.scanner import get_scanner_agent
from app.agents.tester import get_tester_agent


class Orchestrator:
    def __init__(self, target: str):
        self.target = target
        self.planner = get_planner_agent()
        self.scanner = get_scanner_agent()
        self.tester = get_tester_agent()
        self.critic = get_critic_agent()
        self.reporter = get_reporter_agent()

    def _create_tasks(self):
        plan_task = Task(
            description=f"Analyze the target: {self.target}. Develop a stealthy reconnaissance plan.", # noqa: E501
            expected_output="A prioritized list of scanning objectives and OODA-based strategy.", # noqa: E501
            agent=self.planner
        )

        scan_task = Task(
            description="Based on the plan, generate precise Nmap/FFUF commands to identify services.", # noqa: E501
            expected_output="A list of specific CLI commands ready for validation.",
            agent=self.scanner,
            context=[plan_task]
        )

        critic_task = Task(
            description="Review the commands generated by the scanner. Ensure they are safe and syntactically correct.", # noqa: E501
            expected_output="A list of approved, safe-to-execute commands.",
            agent=self.critic,
            context=[scan_task]
        )

        report_task = Task(
            description="Summarize the entire mission strategy and the approved technical steps.", # noqa: E501
            expected_output="A structured final report in JSON/Markdown format.",
            agent=self.reporter,
            context=[plan_task, critic_task]
        )

        return [plan_task, scan_task, critic_task, report_task]

    def run(self):
        tasks = self._create_tasks()

        talos_crew = Crew(
            agents=[self.planner, self.scanner, self.critic, self.reporter],
            tasks=tasks,
            process=Process.sequential,
            verbose=True
        )

        return talos_crew.kickoff()
