from typing import Optional

from app.schemas.report import MissionReport
from crewai import Crew, Process, Task

from app.agents.critic import get_critic_agent
from app.agents.planner import get_planner_agent
from app.agents.reporter import get_reporter_agent
from app.agents.scanner import get_scanner_agent
from app.agents.tester import get_tester_agent


class Orchestrator:
    def __init__(self, target: str, user_prompt: Optional[str] = None):
        self.target = target
        self.planner = get_planner_agent()
        self.scanner = get_scanner_agent()
        self.tester = get_tester_agent()
        self.critic = get_critic_agent()
        self.reporter = get_reporter_agent()
        self.user_prompt = user_prompt or \
        """Perform a standard comprehensive security analysis."""

    def _create_tasks(self):
        plan_task = Task(
            agent=self.planner,
            description=(
                f"""Target: {self.target}\n
                User Instructions: {self.user_prompt}\n\n
                Develop a high-level pentest strategy based on these instructions."""
            ),
            expected_output="""A prioritized list of scanning objectives
            and OODA-based strategy.""",
        )

        scan_task = Task(
            agent=self.scanner,
            context=[plan_task],
            description=f"""Based on the plan, generate precise Nmap/FFUF commands
            to identify services ONLY for the target {self.target}.""",
            expected_output="""A list of specific CLI commands
            ready for validation using the correct target."""
        )

        critic_task = Task(
            agent=self.critic,
            context=[scan_task],
            description="""Review the commands generated by the scanner.
            Ensure they are safe and syntactically correct.""",
            expected_output="A list of approved, safe-to-execute commands."
        )

        report_task = Task(
            agent=self.reporter,
            context=[plan_task, critic_task],
            output_pydantic=MissionReport,
            description="""Summarize the entire mission strategy
            and the approved technical steps.""",
            expected_output="""A raw, valid JSON object.
            IMPORTANT: Do not wrap the output in markdown code blocks (no ```json).
            Do not include any conversational text before or after the JSON.
            Ensure all strings are plain text without unnecessary escape sequences."""
        )

        return [plan_task, scan_task, critic_task, report_task]

    def run(self):
        tasks = self._create_tasks()

        talos_crew = Crew(
            tasks=tasks,
            verbose=True,
            memory=False,
            process=Process.sequential,
            agents=[self.planner, self.scanner, self.critic, self.reporter]
        )

        return talos_crew.kickoff()
